# Generated by Django 4.2 on 2023-04-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='somethings',
            field=models.CharField(default='a', max_length=20),
        ),
    ]
